extends SceneTree

const RewardService = preload("res://actors/RewardService.gd")
const WalletState = preload("res://actors/WalletState.gd")
const InventoryState = preload("res://actors/InventoryState.gd")
const ItemTemplate = preload("res://actors/ItemTemplate.gd")
const ItemInstance = preload("res://actors/ItemInstance.gd")
const TestProtocol = preload("res://tests/TestProtocol.gd")

func _init():
	var test = TestProtocol.new()
	var rewards = RewardService.new()
	var wallet = WalletState.new().new_state()
	var inventory = InventoryState.new().normalize(InventoryState.new().new_state())
	var herb = ItemTemplate.new().normalize({"id": "item.herb", "stack_limit": 10})
	var granted = rewards.grant(wallet, inventory, "snake.1", 100, 10, herb, 2)
	test.expect(granted.ok and granted.wallet.money == 100 and granted.wallet.juntuan == 10 and granted.inventory.slots[0].quantity == 2, "grants wallet and inventory rewards atomically")
	var duplicate = rewards.grant(granted.wallet, granted.inventory, "snake.1", 100, 10, herb, 2)
	test.expect(duplicate.ok and duplicate.duplicate and duplicate.wallet.money == 100 and duplicate.inventory.slots[0].quantity == 2, "duplicate reward ID grants exactly once")
	var full = InventoryState.new().new_state()
	for index in range(InventoryState.SLOT_COUNT):
		full.slots.append(ItemInstance.new().new_stack(herb, 10))
	full = InventoryState.new().normalize(full)
	var full_reward = rewards.grant(wallet, full, "snake.2", 100, 10, herb, 1)
	test.expect(not full_reward.ok and full_reward.wallet.money == 0 and full_reward.inventory.slots[0].quantity == 10, "full inventory prevents every reward component from committing")
	var currency_only = rewards.grant(wallet, inventory, "boss.1", 1000, 100)
	test.expect(currency_only.ok and currency_only.wallet.money == 1000 and currency_only.inventory.slots[0].empty(), "supports atomic currency-only rewards")
	var ore = ItemTemplate.new().normalize({"id": "item.ore", "stack_limit": 10})
	var many = rewards.grant_many(wallet, inventory, "boss.2", 50, 0, [{"template": herb, "quantity": 2}, {"template": ore, "quantity": 3}])
	test.expect(many.ok and many.wallet.money == 50 and many.inventory.slots[0].template_id == "item.herb" and many.inventory.slots[1].template_id == "item.ore", "grants multiple drops in one atomic operation")
	var many_full = rewards.grant_many(wallet, full, "boss.3", 50, 0, [{"template": herb, "quantity": 1}, {"template": ore, "quantity": 1}])
	test.expect(not many_full.ok and many_full.wallet.money == 0 and many_full.inventory.slots[0].quantity == 10, "full inventory rolls back every multi-drop reward component")
	test.finish(self, "reward_service")
